// automatically generated by the FlatBuffers compiler, do not modify

package com.alicloud.openservices.tablestore.core.protocol.timeseries.flatbuffer;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FieldValues extends Table {
  public static FieldValues getRootAsFieldValues(ByteBuffer _bb) { return getRootAsFieldValues(_bb, new FieldValues()); }
  public static FieldValues getRootAsFieldValues(ByteBuffer _bb, FieldValues obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public FieldValues __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long longValues(int j) { int o = __offset(4); return o != 0 ? bb.getLong(__vector(o) + j * 8) : 0; }
  public int longValuesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer longValuesAsByteBuffer() { return __vector_as_bytebuffer(4, 8); }
  public ByteBuffer longValuesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 8); }
  public boolean boolValues(int j) { int o = __offset(6); return o != 0 ? 0!=bb.get(__vector(o) + j * 1) : false; }
  public int boolValuesLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer boolValuesAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer boolValuesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public double doubleValues(int j) { int o = __offset(8); return o != 0 ? bb.getDouble(__vector(o) + j * 8) : 0; }
  public int doubleValuesLength() { int o = __offset(8); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer doubleValuesAsByteBuffer() { return __vector_as_bytebuffer(8, 8); }
  public ByteBuffer doubleValuesInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 8); }
  public String stringValues(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int stringValuesLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public BytesValue binaryValues(int j) { return binaryValues(new BytesValue(), j); }
  public BytesValue binaryValues(BytesValue obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int binaryValuesLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }

  public static int createFieldValues(FlatBufferBuilder builder,
      int long_valuesOffset,
      int bool_valuesOffset,
      int double_valuesOffset,
      int string_valuesOffset,
      int binary_valuesOffset) {
    builder.startObject(5);
    FieldValues.addBinaryValues(builder, binary_valuesOffset);
    FieldValues.addStringValues(builder, string_valuesOffset);
    FieldValues.addDoubleValues(builder, double_valuesOffset);
    FieldValues.addBoolValues(builder, bool_valuesOffset);
    FieldValues.addLongValues(builder, long_valuesOffset);
    return FieldValues.endFieldValues(builder);
  }

  public static void startFieldValues(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addLongValues(FlatBufferBuilder builder, int longValuesOffset) { builder.addOffset(0, longValuesOffset, 0); }
  public static int createLongValuesVector(FlatBufferBuilder builder, long[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addLong(data[i]); return builder.endVector(); }
  public static void startLongValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addBoolValues(FlatBufferBuilder builder, int boolValuesOffset) { builder.addOffset(1, boolValuesOffset, 0); }
  public static int createBoolValuesVector(FlatBufferBuilder builder, boolean[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addBoolean(data[i]); return builder.endVector(); }
  public static void startBoolValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static void addDoubleValues(FlatBufferBuilder builder, int doubleValuesOffset) { builder.addOffset(2, doubleValuesOffset, 0); }
  public static int createDoubleValuesVector(FlatBufferBuilder builder, double[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addDouble(data[i]); return builder.endVector(); }
  public static void startDoubleValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static void addStringValues(FlatBufferBuilder builder, int stringValuesOffset) { builder.addOffset(3, stringValuesOffset, 0); }
  public static int createStringValuesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startStringValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addBinaryValues(FlatBufferBuilder builder, int binaryValuesOffset) { builder.addOffset(4, binaryValuesOffset, 0); }
  public static int createBinaryValuesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startBinaryValuesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endFieldValues(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

