// automatically generated by the FlatBuffers compiler, do not modify

package com.alicloud.openservices.tablestore.core.protocol.sql.flatbuffers;

public final class DataType {
  private DataType() { }
  public static final byte NONE = 0;
  public static final byte LONG = 1;
  public static final byte BOOLEAN = 2;
  public static final byte DOUBLE = 3;
  public static final byte STRING = 4;
  public static final byte BINARY = 5;
  public static final byte STRING_RLE = 6;

  public static final String[] names = { "NONE", "LONG", "BOOLEAN", "DOUBLE", "STRING", "BINARY", "STRING_RLE", };

  public static String name(int e) { return names[e]; }
}

