// automatically generated by the FlatBuffers compiler, do not modify

package com.alicloud.openservices.tablestore.core.protocol.sql.flatbuffers;

public final class LogicType {
  private LogicType() { }
  public static final byte NONE = 0;
  public static final byte DATETIME = 1;
  public static final byte DATE = 2;
  public static final byte TIME = 3;

  public static final String[] names = { "NONE", "DATETIME", "DATE", "TIME", };

  public static String name(int e) { return names[e]; }
}

