// automatically generated by the FlatBuffers compiler, do not modify

package com.alicloud.openservices.tablestore.core.protocol.sql.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SQLResponseColumns extends Table {
  public static SQLResponseColumns getRootAsSQLResponseColumns(ByteBuffer _bb) { return getRootAsSQLResponseColumns(_bb, new SQLResponseColumns()); }
  public static SQLResponseColumns getRootAsSQLResponseColumns(ByteBuffer _bb, SQLResponseColumns obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; vtable_start = bb_pos - bb.getInt(bb_pos); vtable_size = bb.getShort(vtable_start); }
  public SQLResponseColumns __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SQLResponseColumn columns(int j) { return columns(new SQLResponseColumn(), j); }
  public SQLResponseColumn columns(SQLResponseColumn obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int columnsLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public long rowCount() { int o = __offset(6); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createSQLResponseColumns(FlatBufferBuilder builder,
      int columnsOffset,
      long row_count) {
    builder.startObject(2);
    SQLResponseColumns.addRowCount(builder, row_count);
    SQLResponseColumns.addColumns(builder, columnsOffset);
    return SQLResponseColumns.endSQLResponseColumns(builder);
  }

  public static void startSQLResponseColumns(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addColumns(FlatBufferBuilder builder, int columnsOffset) { builder.addOffset(0, columnsOffset, 0); }
  public static int createColumnsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startColumnsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRowCount(FlatBufferBuilder builder, long rowCount) { builder.addLong(1, rowCount, 0L); }
  public static int endSQLResponseColumns(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishSQLResponseColumnsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedSQLResponseColumnsBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }
}

